CREATE VIEW S_CABLATI AS SELECT 
	repeat(' ',2) AS TIPO4F,
	left(ltrim(to_char(extract(year from current_date),'0000')),2) as STSO4F,
	i.ANNO_STAGIONE as STOA4F,
	i.STAGIONE AS STOS4F,
	'08' AS LIVE4F,
	'50' AS TIVE4F,
	'50' AS STVE4F,
	'77' AS EVEN4F,
	i."CODICE_INVIO" AS RIES4F,
	'00000' AS NRIE4F,
	ltrim(to_char(extract(day from current_date),'00')) as REGG4F,
	ltrim(to_char(extract(month from current_date),'00')) as REMM4F,
	left(ltrim(to_char(extract(year from current_date),'0000')),2) as RESS4F,
	right(ltrim(to_char(extract(year from current_date),'0000')),2) as REAA4F,
	'01' AS DEST4F,
	repeat(' ',4) AS FLDE4F,
	repeat(' ',2) AS STAT4F,
	'000' AS COMB4F,
	repeat(' ',6) AS CPA14F,
	'000' AS MISU4F,
	repeat(' ',13) AS DPST4F_etc,
	ltrim(to_char(extract(day from current_date),'00')) as CGGD4F,
	ltrim(to_char(extract(month from current_date),'00')) as CMMD4F,
	left(ltrim(to_char(extract(year from current_date),'0000')),2) as CSSD4F,
	right(ltrim(to_char(extract(year from current_date),'0000')),2) as CAAD4F,
	ltrim(to_char(extract(day from current_date),'00')) as CGGA4F,
	ltrim(to_char(extract(month from current_date),'00')) as CMMA4F,
	left(ltrim(to_char(extract(year from current_date),'0000')),2) as CSSA4F,
	right(ltrim(to_char(extract(year from current_date),'0000')),2) as CAAA4F,
	'0000000000000' AS PLUA4F,
	repeat(' ',14) AS LSCD4F_etc,
	ltrim(to_char(extract(day from current_date),'00')) as DESG4F,
	ltrim(to_char(extract(month from current_date),'00')) as DESM4F,
	left(ltrim(to_char(extract(year from current_date),'0000')),2) as DESS4F,
	right(ltrim(to_char(extract(year from current_date),'0000')),2) as DESA4F,
	'1159' AS HHMM4F,
	repeat(' ',50) AS COMM4F,
	repeat(' ',20) AS PONU4F,
	repeat(' ',10) AS FLV04F_etc
FROM "S_CODICE_INVIO" i;