CREATE TABLE I_Allocation_Qty (
	 Stylecolor         VARCHAR(50)
	,Location           vARCHAR(50)
	,Typology           vaRCHAR(50)
	,EventYear          varCHAR(50)
	,Allocation_Qty     varcHAR(50)
);

CREATE TABLE I_Allocation_Local_Val (
	Stylecolor	           VARCHAR(50)
	,Location	           VARCHAR(50)
	,Typology	           VARCHAR(50)
	,EventYear	           VARCHAR(50)
	,Allocation_Local_Val  VARCHAR(50)
);

CREATE TABLE I_Allocation_Val (
	Stylecolor	    VARCHAR(50)
	,Location	    VARCHAR(50)
	,Typology	    VARCHAR(50)
	,EventYear	    VARCHAR(50)
	,Allocation Val  VARCHAR(50)
);


CREATE TABLE I_Item (     
	 Item	                           VARCHAR(50) 
	,Item_Desc	                       VARCHAR(50)
	,Color	                           VARCHAR(50)
	,Color_Desc                        VARCHAR(50)
	,Progr_Size	                       VARCHAR(50)
	,Progr_Size_Desc	               VARCHAR(50)
	,Range_Position	                   VARCHAR(50)
	,Range_Position_Desc	           VARCHAR(50)
	,Department	                       VARCHAR(50)
	,Department_Desc	               VARCHAR(50)
	,Planning_Attribute	               VARCHAR(50)
	,Planning_Attribute_Desc	       VARCHAR(50)
	,Material	                       VARCHAR(50)
	,Material_Desc	                   VARCHAR(50)
	,Stylecolor	                       VARCHAR(50)
	,Stylecolor_Desc	               VARCHAR(50)
	,Size_Range	                       VARCHAR(50)
	,Size_Range_Desc	               VARCHAR(50)
	,Style	                           VARCHAR(50)
	,Style_Desc	                       VARCHAR(50)
	,Size	                           VARCHAR(50)
	,Size_Desc	                       VARCHAR(50)
	,All_items	                       VARCHAR(50)
	,All_items_Desc	                   VARCHAR(50)
	,Class	                           VARCHAR(50)
	,Class_Desc	                       VARCHAR(50)
	,Iconic_material	               VARCHAR(50)
	,Iconic_material_Desc	           VARCHAR(50)
	,Secondary_Attribute_1	           VARCHAR(50)
	,Secondary_Attribute_1_Desc	       VARCHAR(50)
	,Subclass	                       VARCHAR(50)
	,Subclass_Desc	                   VARCHAR(50)
	,SubDepartment	                   VARCHAR(50)
	,SubDepartment_Desc	               VARCHAR(50)
	,Fitting	                       VARCHAR(50)
	,Fitting_Desc                      VARCHAR(50)
	,StyleMaterial	                   VARCHAR(50)
	,StyleMaterial_Desc	               VARCHAR(50)
	,Macro_Color	                   VARCHAR(50)
	,Macro_Color_Desc	               VARCHAR(50)
	,Galvanic	                       VARCHAR(50)
	,Galvanic_Desc	                   VARCHAR(50)
	,Fashion_Class	                   VARCHAR(50)
	,Fashion_Class_Desc	               VARCHAR(50)
	,Gender	                           VARCHAR(50)
	,Gender_Desc	                   VARCHAR(50)
	,Shape	                           VARCHAR(50)
	,Shape_Desc	                       VARCHAR(50)
	,Price_Range	                   VARCHAR(50)
	,Price_Range_Desc	               VARCHAR(50)
	,Use_Occasion	                   VARCHAR(50)
	,Use_Occasion_Desc	               VARCHAR(50)
	,Height	                           VARCHAR(50)
	,Height_Desc	                   VARCHAR(50)
	,Function	                       VARCHAR(50)
	,Function_Desc	                   VARCHAR(50)
	,Core_Material	                   VARCHAR(50)
	,Core_Material_Desc	               VARCHAR(50)
	,Color_Mood	                       VARCHAR(50)
	,Color_Mood_Desc	               VARCHAR(50)
	,Name	                           VARCHAR(50)
	,Name_Desc	                       VARCHAR(50)
	,Material_Class	                   VARCHAR(50)
	,Material_Class_Desc	           VARCHAR(50)
	,Product_Size	                   VARCHAR(50)
	,Product_Size_Desc	               VARCHAR(50)
	,Limited_Class	                   VARCHAR(50)
	,Limited_Class_Desc	               VARCHAR(50)
	,Heel_Height	                   VARCHAR(50)
	,Heel_Height_Desc	               VARCHAR(50)
	,Bottle_Size	                   VARCHAR(50)
	,Bottle_Size_Desc	               VARCHAR(50)
	,Key_RP_Attributes	               VARCHAR(50)
	,Key_RP_Attributes_Desc	           VARCHAR(50)
	,Size_progression	               VARCHAR(50)
	,Size_position_13                  VARCHAR(50) 
);


-- da fare la tabella delle locations



